// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr0YznMHk-7cVbmiQhmWm0gy-XmG0Ykxs',
    appId: '1:394284822881:web:cab2aa572281b1bd8b1520',
    messagingSenderId: '394284822881',
    projectId: 'langapp001-737f1',
    authDomain: 'langapp001-737f1.firebaseapp.com',
    storageBucket: 'langapp001-737f1.firebasestorage.app',
    measurementId: 'G-V95NQNBFDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDloi-k6kR3P-xD6JEzgT5gdyMgybBn6Sk',
    appId: '1:394284822881:android:678d6e6fe00a2d8a8b1520',
    messagingSenderId: '394284822881',
    projectId: 'langapp001-737f1',
    storageBucket: 'langapp001-737f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOpaQtugED4FHm9SOesjnefmWFyGTzaKc',
    appId: '1:394284822881:ios:e5a5446db87f03e38b1520',
    messagingSenderId: '394284822881',
    projectId: 'langapp001-737f1',
    storageBucket: 'langapp001-737f1.firebasestorage.app',
    iosBundleId: 'com.example.languageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr0YznMHk-7cVbmiQhmWm0gy-XmG0Ykxs',
    appId: '1:394284822881:web:e262809a321ed5448b1520',
    messagingSenderId: '394284822881',
    projectId: 'langapp001-737f1',
    authDomain: 'langapp001-737f1.firebaseapp.com',
    storageBucket: 'langapp001-737f1.firebasestorage.app',
    measurementId: 'G-FG6J8JYZ67',
  );
}
